SET IDENTITY_INSERT [dbo].[gate] ON 
GO

BEGIN TRANSACTION
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        9 , 
        'tester1' , 
        '2012-09-26 15:42:11' , 
        '543b69df3d4c1a32805a6b8a423ba8c2' , 
        'Tester' , 
        'One' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'TouyecYU4gKCeFdin2rym' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        'z' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        10 , 
        'tester2' , 
        '2012-09-27 07:04:00' , 
        '3b86fc29c450441f1094fde206e2b5bc' , 
        'Tester' , 
        'Two' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'Rh1gATqQKjSJE4vYXITHl' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        11 , 
        'tester3' , 
        '2012-09-27 14:42:14' , 
        '48c6b1d5052ab8e76ab6745428752633' , 
        'Tester' , 
        'Three' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        '0L6SH8hWeY0abLS2cZWRE' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        12 , 
        'tester4' , 
        '2012-09-28 08:00:46' , 
        'e0e7d5cc8d246af00e6274ee9f705596' , 
        'Tester' , 
        'Four' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'l3aYo55u2ExhKiiIpbTY4' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        'z' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        13 , 
        'Group1' , 
        '2012-09-28 08:01:33' , 
        '522547446283ab7837ab6ea888995bd6' , 
        'Group One' , 
        'Group One' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        '1zs98q4lsnpGfhNlgTvZD' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'group   ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        14 , 
        'Tester5' , 
        '2012-09-28 08:03:37' , 
        'd3b1bc9c02ce5d006bce9b6c57d677fd' , 
        'Tester' , 
        'Five' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'v57TbzngEVaWRY7jvU3x9' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        15 , 
        'Group2' , 
        '2012-09-28 08:04:27' , 
        '8de79d80f9a99aa4adf606364a4daaa3' , 
        'Group Two' , 
        'Group Two' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'foo@bar.zzz' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'S8AxrPqxMC4hurLP1nN5p' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'group   ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        16 , 
        'tester6' , 
        '2012-09-28 12:29:11' , 
        'd06ba993bcf38d408d151c2f9b93f4db' , 
        'Tester' , 
        'Six' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'wBnY6AaYB8cjus3FFBOqJ' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        17 , 
        'Tester7' , 
        '2012-09-28 12:30:52' , 
        'b77b0fbfc7594a50c751a2ca653708a7' , 
        'Tester' , 
        'Seven' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'm6OjXYgIP7fki97At5FP2' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        18 , 
        'tester8' , 
        '2012-09-28 12:35:37' , 
        'ff0a26d6017023ab1056f273c8ec2591' , 
        'Tester' , 
        'Eight' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'D0sRywNRzBQYewFbXZXKF' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        19 , 
        'tester9' , 
        '2012-09-28 12:36:15' , 
        '9da6c6937e0ab9aecca67d24946ee2da' , 
        'Tester' , 
        'Nine' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'H8E5bRYwP7tv6jHJhnfaA' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        20 , 
        'tester10' , 
        '2012-09-28 12:55:47' , 
        'eea75f1db8897ff9a8719b84ddc112a8' , 
        'Alchemy' , 
        'Ten' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'OgW1vetrhrUVjEyt7XmJk' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        21 , 
        'tester11' , 
        '2012-09-28 12:56:25' , 
        '93cb60c0490626b0a5383a3ced7837b2' , 
        'Tester' , 
        'Eleven' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'Tw5ASloyrDucfg6TeU75H' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
INSERT INTO [dbo].[gate]
     (
        uid                   ,
        lname                 ,
        requestdate           ,
        pwd                   ,
        firstname             ,
        lastname              ,
        country               ,
        state                 ,
        chall_qst             ,
        chall_ans             ,
        curr_email_addr       ,
        confrm_email_sent_flg ,
        inactive_flg          ,
        contributor_name      ,
        contributor_url       ,
        contributor_short_bio ,
        guid                  ,
        mbrshpstat            ,
        chall_hint            ,
        mbrshpconfirm         ,
        cstm1                 ,
        cstm2                 ,
        cstm3                 ,
        referral              ,
        entity_typ_flg        ,
        admin_flg             ,
        skin_bg               ,
        skin_tabs             
     ) 
VALUES
     (
        22 , 
        'tester14' , 
        '2012-10-01 11:44:55' , 
        'b4bbadc48f9d5099d21c7bdc57f0bd7d' , 
        'Tester' , 
        'Fourteen' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'ericm1000@comcast.net' , 
        NULL , 
        ' ' , 
        NULL , 
        NULL , 
        NULL , 
        'ycMOfMfMJPpuXLx1AUbCp' , 
        'y' , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        NULL , 
        'user    ' , 
        ' ' , 
        NULL , 
        'A' 
     ) 
GO
COMMIT TRANSACTION
GO
SET IDENTITY_INSERT [dbo].[gate] OFF 
GO
