CREATE TABLE dbo.lnks_itm
     ( 
        member_uid     INT             NOT NULL  , 
        mnu_itm1       VARCHAR(15)         NULL  , 
        public_flg1    CHAR(1)             NULL  , 
        archive_flg1   CHAR(1)             NULL  , 
        mnu_itm2       VARCHAR(15)         NULL  , 
        public_flg2    CHAR(1)             NULL  , 
        archive_flg2   CHAR(1)             NULL  , 
        mnu_itm3       VARCHAR(15)         NULL  , 
        public_flg3    CHAR(1)             NULL  , 
        archive_flg3   CHAR(1)             NULL  , 
        mnu_itm4       VARCHAR(15)         NULL  , 
        public_flg4    CHAR(1)             NULL  , 
        archive_flg4   CHAR(1)             NULL  , 
        mnu_itm5       VARCHAR(15)         NULL  , 
        public_flg5    CHAR(1)             NULL  , 
        archive_flg5   CHAR(1)             NULL  , 
        mnu_itm6       VARCHAR(15)         NULL  , 
        public_flg6    CHAR(1)             NULL  , 
        archive_flg6   CHAR(1)             NULL  , 
        mnu_itm7       VARCHAR(15)         NULL  , 
        public_flg7    CHAR(1)             NULL  , 
        archive_flg7   CHAR(1)             NULL  , 
        mnu_itm8       VARCHAR(15)         NULL  , 
        public_flg8    CHAR(1)             NULL  , 
        archive_flg8   CHAR(1)             NULL  , 
        ico1url        VARCHAR(225)        NULL  , 
        ico1img        VARCHAR(100)        NULL  , 
        ico2url        VARCHAR(225)        NULL  , 
        ico2img        VARCHAR(100)        NULL  , 
        ico3url        VARCHAR(225)        NULL  , 
        ico3img        VARCHAR(100)        NULL  , 
        ico4url        VARCHAR(225)        NULL  , 
        ico4img        VARCHAR(100)        NULL  , 
        ico1wndflg     CHAR(1)             NULL  , 
        ico2wndflg     CHAR(1)             NULL  , 
        ico3wndflg     CHAR(1)             NULL  , 
        ico4wndflg     CHAR(1)             NULL  , 
        ico5url        VARCHAR(225)        NULL  , 
        ico5img        VARCHAR(100)        NULL  , 
        ico6url        VARCHAR(225)        NULL  , 
        ico6img        VARCHAR(100)        NULL  , 
        ico7url        VARCHAR(225)        NULL  , 
        ico7img        VARCHAR(100)        NULL  , 
        ico8url        VARCHAR(225)        NULL  , 
        ico8img        VARCHAR(100)        NULL  , 
        ico5wndflg     CHAR(1)             NULL  , 
        ico6wndflg     CHAR(1)             NULL  , 
        ico7wndflg     CHAR(1)             NULL  , 
        ico8wndflg     CHAR(1)             NULL  , 
        link_flg1      CHAR(1)             NULL  , 
        link_flg2      CHAR(1)             NULL  , 
        link_flg3      CHAR(1)             NULL  , 
        link_flg4      CHAR(1)             NULL  , 
        link_flg5      CHAR(1)             NULL  , 
        link_flg6      CHAR(1)             NULL  , 
        link_flg7      CHAR(1)             NULL  , 
        link_flg8      CHAR(1)             NULL  , 
        lib_flg1       CHAR(1)             NULL  , 
        lib_flg2       CHAR(1)             NULL  , 
        lib_flg3       CHAR(1)             NULL  , 
        lib_flg4       CHAR(1)             NULL  , 
        lib_flg5       CHAR(1)             NULL  , 
        lib_flg6       CHAR(1)             NULL  , 
        lib_flg7       CHAR(1)             NULL  , 
        lib_flg8       CHAR(1)             NULL  , 
        mnu_name       VARCHAR(25)         NULL  , 
        CONSTRAINT PK_lnks_itm PRIMARY KEY CLUSTERED (member_uid ASC) ON [PRIMARY] 
     )
GO 

